name: "Demo Test"

on:
  push:
    branches: ["master"]
env:
    ${{env.QA}}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'windows-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build

    - name: 'Test project'
      run: dotnet test --environment ${{vars.BROWSERNAME}}
